title: GLC_Replication
description: Here are all our replication results(figures) and the original results from the paper. For further explanation of each, it will be shown in the readme file.
show_downloads: true
theme: jekyll-theme-minimal
gallery_images:
  - image_path: /assets/img/figure_1.jpg
  - image_path: /assets/img/figure_2.jpg